services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.6
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_CLIENT_PORT: 2181
    networks:
      - kafka-net
    volumes:
      - zookeeper-data:/var/lib/zookeeper/data
    healthcheck:
      test: ["CMD", "echo", "ruok", "|", "nc", "-w", "3", "zookeeper", "2181", "|", "grep", "imok"]
      interval: 10s
      retries: 3
      start_period: 10s
      timeout: 5s
  kafka:
    image: confluentinc/cp-kafka:7.4.6
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_NAMES: PLAINTEXT,OUTSIDE
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,OUTSIDE://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,OUTSIDE://YOUR_HOST_IP:9093
      KAFKA_CONFLUENT_SUPPORT_METRICS_ENABLE: "false"
      KAFKA_MESSAGE_MAX_BYTES: 2000000000
      KAFKA_REPLICA_FETCH_MAX_BYTES: 2000000000
      KAFKA_REPLICA_MAX_LOG_SIZE: 2000000000
    ports:
      - "9092:9092"
      - "9093:9093"
    networks:
      - kafka-net
    volumes:
      - kafka-data:/var/lib/kafka/data
    healthcheck:
      test: ["CMD", "kafka-broker-api-versions.sh", "--bootstrap-server", "kafka:9092"]
      interval: 10s
      retries: 3
      start_period: 10s
      timeout: 5s
networks:
  kafka-net:
    driver: bridge
volumes:
  zookeeper-data:
    driver: local
  kafka-data:
    driver: local